name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: test

    env:
      API_URL: ${{ secrets.API_URL }}
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASS: ${{ secrets.TEST_PASS }}
      GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
      GOOGLE_PASS: ${{ secrets.GOOGLE_PASS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
      - name: Debug environment variables
        run: |
          echo "Secrets available:"
          echo "${{ secrets.TEST_USER != '' && '✅ TEST_USER found' || '❌ TEST_USER missing' }}"
          echo "${{ secrets.BASE_URL != '' && '✅ API_URL found' || '❌ API_URL missing' }}"
          echo "${{ secrets.API_URL != '' && '✅ API_URL found' || '❌ API_URL missing' }}"
          echo "${{ secrets.TEST_PASS != '' && '✅ GOOGLE_USER found' || '❌ GOOGLE_USER missing' }}"
          echo "${{ secrets.SLACK_WEBHOOK_URL != '' && '✅ GOOGLE_USER found' || '❌ GOOGLE_USER missing' }}"


      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ✅ Run Playwright tests with CTRF + HTML reports
      - name: Run Playwright tests
        run: |
          echo $TEST_USER
          echo $TEST_PASSWORD
          npx playwright test
          ls
        continue-on-error: true

      # ✅ Send Slack Notification (using your Slack Webhook)
      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          pwd
          if [ -f ./ctrf/ctrf-report.json ]; then
            npx slack-ctrf results ./ctrf/ctrf-report.json --webhook-url ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "⚠️ CTRF JSON file not found. Skipping Slack notification."
          fi
